Filter:
  Latitude:
   min: 577086800
   max: 577091300

  Longitude:
   min: 119800500
   max: 119804800

  Accuracy:
    min: 4000
    max: 10000
  Time:
    min: "2015-03-20 00:00:00"
    max: "2015-03-20 23:00:00"

outputs:
 - type: "jpeg"
   filename: "output.jpg"
   width: 1024
   height: 1024
   circleSize: 10
   opacity: 128

 - type: "json"
   filename: "filtered_data.json"

 - type: "csv"
   filename: "human.csv"

 - type: "timeinregion"
   filename: "atwork"
   Filter:
     Latitude:
       min: 577086800
       max: 577091300

     Longitude:
       min: 119800500
       max: 119804800

     Accuracy:
       min: 4000
       max: 10000
     Time:
       min: "2015-01-01 00:00:00"
       max: "2016-12-13 00:00:00"


inputs:
 - path: Platshistorik.json
   type: json
